name: alice-twitter
version: 0.1.0

dependencies:
- aeson
- alice-analysis
- async-timer
- base
- bytestring
- interpolate
- lens
- logging
- random-shuffle
- text
- twitter-conduit
- twitter-types

ghc-options:
- -Wall
- -Werror

executable:
  source-dirs: .
  main: Main.hs
