# Twitter bot project definition

name: alice-twitter # name used in dependency lists
version: 0.2.0 # any change to the first two numbers indicates breaking change; third number is minor version

dependencies:
- aeson # JSON library
- alice-analysis # our analysis code
- async-timer # timer library
- base # base Haskell library
- bytestring # byte-handling
- file-embed # embeds files in code at compile time
- lens # structure modification
- logging # logging utility
- random-shuffle # randomly shuffle lists
- text # core string library
- twitter-conduit # twitter api utility
- twitter-types # twitter api Haskell definitions

ghc-options:
- -Wall # include all warnings
- -Werror # make warnings an error

executable:
  source-dirs: . # look for Haskell files in current directory
  main: Main.hs # this is the file with the `main` function
