name: alice-analysis
version: 0.1.0
dependencies:
- base
- bytestring
- containers
- filepath
- lens
- pdf-toolbox-document
- text
ghc-options:
- -Wall
- -Werror
library:
  source-dirs: source
executable:
  source-dirs: app
  main: Main.hs
  dependencies:
  - alice-analysis
tests:
  alice-analysis-tests:
    source-dirs: test
    main: Main.hs
    dependencies:
    - alice-analysis
    - hedgehog
